Use self-hosted runner

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -6,22 +6,17 @@ on:
       - main
 
 env:
-  VERSION: v${{ github.run_number }}
+  IMAGE_TAG: v${{ github.run_number }}
 
 jobs:
   build-deploy:
-
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
 
     steps:
-
-      - name: Checkout
+      - name: Checkout Source
         uses: actions/checkout@v4
 
-      - name: Setup Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Login to DockerHub
+      - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
@@ -34,13 +29,14 @@ jobs:
       - name: Build Backend
         run: |
           docker build \
-          -t ${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.VERSION }} \
-          ./backend
+            -t ${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.IMAGE_TAG }} \
+            -t ${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:latest \
+            ./backend
 
       - name: Push Backend
         run: |
-          docker push \
-          ${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.VERSION }}
+          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.IMAGE_TAG }}
+          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:latest
 
       #################################################
       # Frontend
@@ -49,34 +45,38 @@ jobs:
       - name: Build Frontend
         run: |
           docker build \
-          -t ${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.VERSION }} \
-          ./frontend
+            -t ${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.IMAGE_TAG }} \
+            -t ${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:latest \
+            ./frontend
 
       - name: Push Frontend
         run: |
-          docker push \
-          ${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.VERSION }}
+          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.IMAGE_TAG }}
+          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:latest
 
       #################################################
       # Deploy to Kubernetes
       #################################################
 
-      - name: Deploy
-        uses: appleboy/ssh-action@v1.2.2
+      - name: Deploy Backend
+        run: |
+          kubectl set image deployment/backend \
+            backend=${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.IMAGE_TAG }}
 
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USER }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
+      - name: Deploy Frontend
+        run: |
+          kubectl set image deployment/frontend \
+            frontend=${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.IMAGE_TAG }}
 
-          script: |
+      - name: Wait for Rollout
+        run: |
+          kubectl rollout status deployment/backend
+          kubectl rollout status deployment/frontend
 
-            kubectl set image deployment/backend \
-            backend=${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.VERSION }}
+      #################################################
+      # Cleanup old Docker images (optional)
+      #################################################
 
-            kubectl set image deployment/frontend \
-            frontend=${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.VERSION }}
-
-            kubectl rollout status deployment/backend
-
-            kubectl rollout status deployment/frontend
+      - name: Cleanup
+        run: |
+          docker image prune -af || true
